Change identifier from 'name' to 'id' for PCI Compliance
shatran/card-react pull request #28
Opened 2017-01-31 22:06 UTC by TechnicalBro

While attempting integration with Stripe using this component I noticed there was an issue regarding the name attribute being specifically requested.

Another user (@sylv3r) previously forked the repo with a quick fix to integrate usage, though only modified the .JS files from the compiled version.

I simply integrated them with CJSX for build, updated the example, and forth.

I believe it to be highly beneficial for the project and its users, as most integrate this interface with an alternate service as opposed to their own PCI Compliant integrations.

2017-01-31 22:43 UTC, shatran requested changes

2017-01-31 22:43 UTC, shatran commented on src/components/card-react-form-container.cjsx
> +      if (child.props and child.props.id)
@TechnicalBro isn't this forcing the attribute to be id?

2017-01-31 22:43 UTC, shatran commented on lib/card-react-form-container.js
> +          if (child.props && child.props.id) {
@TechnicalBro same here, isn't this forcing the attribute to be id?

2017-01-31 23:02 UTC, sylv3r commented
Thanks for the credit @TechnicalBro
Indeed, my fork wasn't ready for a PR yet, nice work with this one.

I also noticed this *huge* problem which is basically making this component useless for submitting sensible informations like credit card data ... which is actually its main purpose !

I strongly encourage to merge this PR asap.

2017-01-31 23:04 UTC, sylv3r commented on lib/card-react-form-container.js
> +          if (child.props && child.props.id) {
@shatran @TechnicalBro indeed, should be
`if (child.props && inputAttribute) {`
That's a typo I guess ;)

2017-01-31 23:06 UTC, sylv3r commented on src/components/card-react-form-container.cjsx
> +      if (child.props and child.props.id)
same here 
`if (child.props && inputAttribute) {`
Nice shot @shatran

2017-02-01 00:40 UTC, TechnicalBro commented on lib/card-react-form-container.js
> +          if (child.props && child.props.id) {
I'll merge this up right away- Tossed it together pretty quick :)

2017-02-01 00:47 UTC, TechnicalBro commented
Thanks for the heads up @shatran, @sylv3r !

That variable has been slotted in and should be all that's required to have the identifier specified as part of the form container now!

Hope this helps!

2023-03-20 13:18 UTC, closed without merging